# Weddings, Baby Naming Ceremonies, First Dance Choreography and Funeral Celebrant Services 
# Price List 
# Eat Drink and Be Married 
# Inclusions: A personally written ceremony script, Wedding Information Kit, two to three face to face meetings, one wedding rehearsal, preparation and submission of legal documents and certifications to Births, Deaths and Marriages, presentation of Marriage Certificate, strictly confidential storage of records, performance of legally binding ceremony  and professional liaison with on the day service providers to ensure smooth running of the ceremony

title: Laura Ford Celebrant
email: TBC@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Laura Ford is a celebrant in Sydney and can officiate weddings, funerals and baby naming ceremonies. 
  She also specialises in first dance choreography. 
twitter_username: username
github_username: LauraHFord
minimal_mistakes_skin: mint
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Laura Ford"
  avatar : "/assets/images/laura.jpg"
  bio    : "Northern Beaches-based celebrant."
  email. : celebrant@lauraford.com.au
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/laurahfordcelebrant"

footer:
  links:
  - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/laurahfordcelebrant"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
